//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Authentication No..
        /// </summary>
        internal static string BanckAuthenNo {
            get {
                return ResourceManager.GetString("BanckAuthenNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker.
        /// </summary>
        internal static string Broker {
            get {
                return ResourceManager.GetString("Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Id in Profile :.
        /// </summary>
        internal static string BrokerMailId {
            get {
                return ResourceManager.GetString("BrokerMailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, ensure that your E-mail Id is Updated in the User Profile.
        /// </summary>
        internal static string brokerMsg {
            get {
                return ResourceManager.GetString("brokerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Cancelled.
        /// </summary>
        internal static string cancelledOperation {
            get {
                return ResourceManager.GetString("cancelledOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string closeBtn {
            get {
                return ResourceManager.GetString("closeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwait.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Copy (Personal Use).
        /// </summary>
        internal static string CustomerCopy {
            get {
                return ResourceManager.GetString("CustomerCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customs Duty.
        /// </summary>
        internal static string CustomsDuty {
            get {
                return ResourceManager.GetString("CustomsDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        internal static string Date_Time {
            get {
                return ResourceManager.GetString("Date_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration Number.
        /// </summary>
        internal static string DeclarationNumber {
            get {
                return ResourceManager.GetString("DeclarationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After the completion of all payments, print the Declaration Receipt in Customs System.
        /// </summary>
        internal static string DeclarationRcptMsg {
            get {
                return ResourceManager.GetString("DeclarationRcptMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposits.
        /// </summary>
        internal static string deposits {
            get {
                return ResourceManager.GetString("deposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Failed !!!, KGAC Online Payment Rejected by Bank , Please Try Again later !!!.
        /// </summary>
        internal static string errorSupport {
            get {
                return ResourceManager.GetString("errorSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Payment Operation.
        /// </summary>
        internal static string failedPay {
            get {
                return ResourceManager.GetString("failedPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Clearinghouse Systems.
        /// </summary>
        internal static string GCS {
            get {
                return ResourceManager.GetString("GCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using Kuwait Customs System for Online Payment.
        /// </summary>
        internal static string HeaderMessage {
            get {
                return ResourceManager.GetString("HeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KD.
        /// </summary>
        internal static string kd {
            get {
                return ResourceManager.GetString("kd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Administration of Customs.
        /// </summary>
        internal static string KGAC {
            get {
                return ResourceManager.GetString("KGAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCS eGate.
        /// </summary>
        internal static string Knet {
            get {
                return ResourceManager.GetString("Knet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA.
        /// </summary>
        internal static string KnetInterfaceLanguage {
            get {
                return ResourceManager.GetString("KnetInterfaceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Reference No..
        /// </summary>
        internal static string OLTransId {
            get {
                return ResourceManager.GetString("OLTransId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Integration.
        /// </summary>
        internal static string OnlinePayment {
            get {
                return ResourceManager.GetString("OnlinePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Receipt No..
        /// </summary>
        internal static string OnlineReceiptNo {
            get {
                return ResourceManager.GetString("OnlineReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other Info.
        /// </summary>
        internal static string otherInfo1 {
            get {
                return ResourceManager.GetString("otherInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other Info.
        /// </summary>
        internal static string otherInfo2 {
            get {
                return ResourceManager.GetString("otherInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid By .
        /// </summary>
        internal static string PaidBy {
            get {
                return ResourceManager.GetString("PaidBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid For.
        /// </summary>
        internal static string PaidFor {
            get {
                return ResourceManager.GetString("PaidFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        internal static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Done Successfully.
        /// </summary>
        internal static string PaymentDone {
            get {
                return ResourceManager.GetString("PaymentDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Failed.
        /// </summary>
        internal static string PaymentFailed {
            get {
                return ResourceManager.GetString("PaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment ID.
        /// </summary>
        internal static string PaymentId {
            get {
                return ResourceManager.GetString("PaymentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Payment Not Successfull.
        /// </summary>
        internal static string PaymentRejected {
            get {
                return ResourceManager.GetString("PaymentRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        internal static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        internal static string Proceed {
            get {
                return ResourceManager.GetString("Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Receipt Details.
        /// </summary>
        internal static string ReceiptTitle {
            get {
                return ResourceManager.GetString("ReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number.
        /// </summary>
        internal static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        internal static string TempDeclarationNo {
            get {
                return ResourceManager.GetString("TempDeclarationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Payment Confirmation.
        /// </summary>
        internal static string ThanksMsg {
            get {
                return ResourceManager.GetString("ThanksMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trader.
        /// </summary>
        internal static string Trader {
            get {
                return ResourceManager.GetString("Trader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be directed to K-Net Payment Portal, .
        /// </summary>
        internal static string WarningMessage1 {
            get {
                return ResourceManager.GetString("WarningMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not close or refresh this page or Customs System.
        /// </summary>
        internal static string WarningMessage2 {
            get {
                return ResourceManager.GetString("WarningMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Proceed to open K-Net Payment Gateway, Cancel to return back.
        /// </summary>
        internal static string WarningMessage3 {
            get {
                return ResourceManager.GetString("WarningMessage3", resourceCulture);
            }
        }
    }
}
